//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivePictures.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DivePictures.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Book_Green_48x48 {
            get {
                object obj = ResourceManager.GetObject("Book_Green_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clock_link_32x32 {
            get {
                object obj = ResourceManager.GetObject("clock_link_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap diveinfo {
            get {
                object obj = ResourceManager.GetObject("diveinfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DivingLog {
            get {
                object obj = ResourceManager.GetObject("DivingLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DM3 {
            get {
                object obj = ResourceManager.GetObject("DM3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DM4_48x48 {
            get {
                object obj = ResourceManager.GetObject("DM4_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exiftool {
            get {
                object obj = ResourceManager.GetObject("exiftool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_batch {
            get {
                object obj = ResourceManager.GetObject("file_batch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap format_indent_less {
            get {
                object obj = ResourceManager.GetObject("format_indent_less", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap format_indent_more {
            get {
                object obj = ResourceManager.GetObject("format_indent_more", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageMagick {
            get {
                object obj = ResourceManager.GetObject("ImageMagick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InsertHyperlink {
            get {
                object obj = ResourceManager.GetObject("InsertHyperlink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ms_dos_batch_file {
            get {
                object obj = ResourceManager.GetObject("ms_dos_batch_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewDocument {
            get {
                object obj = ResourceManager.GetObject("NewDocument", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openHS {
            get {
                object obj = ResourceManager.GetObject("openHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picasa_square_16x13 {
            get {
                object obj = ResourceManager.GetObject("picasa_square_16x13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RefreshArrow_Green_32x32_72 {
            get {
                object obj = ResourceManager.GetObject("RefreshArrow_Green_32x32_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RefreshDocViewHS {
            get {
                object obj = ResourceManager.GetObject("RefreshDocViewHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RestartHS {
            get {
                object obj = ResourceManager.GetObject("RestartHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap smarttrak {
            get {
                object obj = ResourceManager.GetObject("smarttrak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap uwatec {
            get {
                object obj = ResourceManager.GetObject("uwatec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Headers&gt;
        ///  &lt;computer&gt;
        ///    &lt;model&gt;16&lt;/model&gt;
        ///    &lt;name&gt;Smart Pro&lt;/name&gt;
        ///    &lt;headerLength&gt;92&lt;/headerLength&gt;
        ///    &lt;header&gt;
        ///      &lt;name&gt;Unknown12&lt;/name&gt;
        ///      &lt;offset&gt;12&lt;/offset&gt;
        ///      &lt;size&gt;4&lt;/size&gt;
        ///    &lt;/header&gt;
        ///    &lt;header&gt;
        ///      &lt;name&gt;Alarms During Dive&lt;/name&gt;
        ///      &lt;offset&gt;16&lt;/offset&gt;
        ///      &lt;size&gt;1&lt;/size&gt;
        ///    &lt;/header&gt;
        ///    &lt;header&gt;
        ///      &lt;name&gt;MB-level at start of dive&lt;/name&gt;
        ///      &lt;offset&gt;17&lt;/offset&gt;
        ///      &lt;size&gt;1&lt;/size&gt;
        ///    &lt;/header&gt;
        ///    &lt;header&gt;
        ///      &lt;name&gt;Maximum Depth&lt;/name&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UwatecSmartHeaders {
            get {
                return ResourceManager.GetString("UwatecSmartHeaders", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap withoutprofile {
            get {
                object obj = ResourceManager.GetObject("withoutprofile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap withprofile {
            get {
                object obj = ResourceManager.GetObject("withprofile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
